# Available variables: %player%, %distance%
bossbar-format: '%player%, %distance%'

# 0 for unlimited range
tracker-range: 0

# WHITELIST, BLACKLIST, OFF
dimension-list-type: WHITELIST
dimension-list:
  - 'world'

# in ticks
# 0 for real time
tracker-refresh-time: 5

tracker-item:
  type: CLOCK
  name: 'PlayerTracker'
  lore:
    - 'right click to cycle players'
    - 'left click to cycle back'
    - 'right click with shift to toggle'
    - 'right click other player while sneaking to disable the tracker on them'
  enchants:
    - 'DURABILITY:1'
  craftable: true
  recipe:
    shape:
      - 'AAA'
      - 'ABA'
      - 'AAA'
    ingredients:
      A: OBSIDIAN
      B: COMPASS

# ACTIONBAR, CHAT, OFF
messages-type: ACTIONBAR
messages:
  cycle: 'Tracking next player: %player%'
  closest: 'Tracking closest player: %player%'
  toggle-on: 'Tracker enabled'
  toggle-off: 'Tracker disabled'
  blacklisted-dimension: 'You cannot use tracker in this world'
  friend: 'Tracker will no longer work on %player%'
  unfriend: 'Tracker will work on %player% again'
  no-players: 'There are no people in range'